name: Publish Python Package

on:
  
  release:
    types: [published]
  workflow_dispatch:
  pull_request:
jobs:
  build:
    name: Build wheels with cibuildwheel
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          cibuildwheel --output-dir dist
        env:
          CIBW_PLATFORM: ${{ matrix.os }}
          CIBW_BUILD: cp3{9,10,11,12}-*
          CIBW_SKIP: pp*,cp38*
  # release:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #       python-version: [3.8, 3.9, 3.10, 3.11, 3.12]
  #   runs-on: ${{ matrix.os }}

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.x'

  #     - name: Install build tools
  #       run: |
  #         python -m pip install --upgrade pip
  #         python -m pip install build twine

  #     - name: Build package
  #       run: |
  #         python -m build --wheel --outdir dist

  # publish:
  #   name: Publish to PyPI
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Upload wheels to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         password: ${{ secrets.PYPI_API_TOKEN }}
  
  publish-test:
    name: Publish to Test PyPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload wheels to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_TEST_USERNAME }}
          password: ${{ secrets.PYPI_TEST_PASSWORD }}
          repository-url: https://test.pypi.org/legacy/